version: "3"

services:
  django:
    restart: on-failure
    build: .
    container_name: jobnest
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    command: >
      sh -c '/usr/local/bin/python3 manage.py migrate --settings=$DJANGO_SETTINGS_MODULE && \
            /usr/local/bin/python3 manage.py createsu --settings=$DJANGO_SETTINGS_MODULE && \
            /usr/local/bin/python3 manage.py collectstatic --noinput --settings=$DJANGO_SETTINGS_MODULE && \
            watchmedo auto-restart --directory=/jobNest/ --pattern=*.py --recursive -- \
            daphne -b 0.0.0.0 -p $PORT JobNest.asgi:application -v2'
    env_file:
      - .env
    volumes:
      - .:/jobNest
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: jobnest-redis
    restart: on-failure
    env_file:
      - .env

