version: "3"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDISCLOUD_URL=redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - .:/JobNest

  redis:
    image: "redis:latest"
