STATUS_ACCEPTED = "ACCEPTED"
STATUS_PENDING = "PENDING"
STATUS_REJECTED = "REJECTED"
STATUS_SCHEDULED_FOR_INTERVIEW = "SCHEDULED FOR INTERVIEW"

STATUS_CHOICES = (
    (STATUS_ACCEPTED, "Accepted"),
    (STATUS_PENDING, "Pending"),
    (STATUS_REJECTED, "Rejected"),
    (STATUS_SCHEDULED_FOR_INTERVIEW, "Scheduled For Interview"),
)
