# Generated by Django 5.0 on 2024-01-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appliedjob',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(null=True, upload_to='static/jobs'),
        ),
    ]
