# Generated by Django 5.0 on 2023-12-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='is_accepted',
            field=models.BooleanField(null=True),
        ),
    ]
