# Generated by Django 5.0.4 on 2024-07-01 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0002_alter_appliedjob_managers_alter_job_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_saved',
        ),
    ]
