# Generated by Django 5.0 on 2023-12-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_appliedjob_is_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjob',
            old_name='scheduled_for_interview_date',
            new_name='interview_date',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='scheduled_for_interview',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='waiting_for_review',
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('SCHEDULED FOR INTERVIEW', 'Scheduled For Interview')], default='PENDING', max_length=255, null=True),
        ),
    ]
