# Generated by Django 5.0 on 2024-01-01 01:47

import django.core.validators
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_scheduled_for_interview_date_appliedjob_interview_date_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appliedjob',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='cv',
            field=models.FileField(upload_to='static/applied_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'pdf', 'docx'])]),
        ),
    ]
