# Generated by Django 5.0 on 2024-01-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_appliedjob_managers_alter_appliedjob_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(null=True, upload_to='jobs'),
        ),
    ]
