# Generated by Django 5.0 on 2023-12-29 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=255, null=True)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='static/tip_author')),
                ('position', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
