# Generated by Django 5.0 on 2024-01-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/tip_author'),
        ),
    ]
