# Generated by Django 5.0 on 2023-12-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='author_image',
            field=models.ImageField(null=True, upload_to='static/tip_author'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
