# Generated by Django 5.0 on 2023-12-30 07:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_alter_tip_author_image_alter_tip_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='misc.faqtype')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
