# Generated by Django 5.0.4 on 2024-07-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.DeleteModel(
            name='OTPSecret',
        ),
    ]
