# Generated by Django 4.2.5 on 2023-11-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_landlord',
            new_name='is_agent',
        ),
    ]
