# Generated by Django 4.2.5 on 2023-11-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenantprofile_agentprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TenantProfile',
            new_name='UserProfile',
        ),
    ]
