# Generated by Django 4.2.5 on 2023-11-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.BooleanField(default=False),
        ),
    ]
