# Generated by Django 4.2.5 on 2023-11-11 10:39

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_provider_user_is_agent_remove_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, validators=[apps.common.validators.validate_phone_number]),
        ),
    ]
