# Generated by Django 4.2.5 on 2023-11-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_profile_gender_agentprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_agent',
        ),
    ]
