# Generated by Django 4.2.5 on 2023-11-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_user_is_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='account_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
