# Generated by Django 4.2.5 on 2023-11-11 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_agentprofile_account_type_profile_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='account_type',
        ),
    ]
