# Generated by Django 4.2.5 on 2023-11-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_agentprofile_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
