# Generated by Django 4.2.5 on 2023-11-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_coins_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='occupation',
        ),
    ]
