# Generated by Django 4.2.5 on 2023-11-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_profile_address_remove_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='coins_available',
            new_name='points_available',
        ),
    ]
