# Generated by Django 4.2.5 on 2023-11-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_coins_available_user_points_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatars'),
        ),
    ]
