# Generated by Django 4.2.5 on 2023-11-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_agentprofile_avatar_remove_profile_avatar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='points_available',
            new_name='coins_available',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/user_avatars'),
        ),
    ]
