# Generated by Django 5.0 on 2024-01-04 00:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('notification_type', models.CharField(choices=[('COMPLETE_PROFILE', 'Complete your profile'), ('PROFILE_UPDATED', 'Profile updated successfully'), ('JOB_APPLIED', 'You have applied for a job'), ('NEW_JOB_AVAILABLE', 'A new job has been posted'), ('APPLICATION_ACCEPTED', 'Congratulations, your application has been accepted'), ('APPLICATION_REJECTED', 'Unfortunately, your application has been rejected'), ('APPLICATION_SCHEDULED_FOR_INTERVIEW', 'Your application has been scheduled for an interview')], max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
