NOTIFICATION_COMPLETE_PROFILE = "COMPLETE_PROFILE"
NOTIFICATION_PROFILE_UPDATED = "PROFILE_UPDATED"
NOTIFICATION_JOB_APPLIED = "JOB_APPLIED"
NOTIFICATION_NEW_JOB_AVAILABLE = "NEW_JOB_AVAILABLE"
NOTIFICATION_APPLICATION_ACCEPTED = "APPLICATION_ACCEPTED"
NOTIFICATION_APPLICATION_REJECTED = "APPLICATION_REJECTED"
NOTIFICATION_APPLICATION_SUBMITTED = "APPLICATION_SUBMITTED"
NOTIFICATION_APPLICATION_SCHEDULED_FOR_INTERVIEW = "APPLICATION_SCHEDULED_FOR_INTERVIEW"

NOTIFICATION_TYPE = (
    (NOTIFICATION_COMPLETE_PROFILE, "Complete your profile"),
    (NOTIFICATION_PROFILE_UPDATED, "Profile updated successfully"),
    (NOTIFICATION_JOB_APPLIED, "You have applied for a job"),
    (NOTIFICATION_NEW_JOB_AVAILABLE, "A new job has been posted"),
    (NOTIFICATION_APPLICATION_ACCEPTED, "Congratulations, your application has been accepted"),
    (NOTIFICATION_APPLICATION_REJECTED, "Unfortunately, your application has been rejected"),
    (NOTIFICATION_APPLICATION_SUBMITTED, "Your application has been submitted and will soon be under review"),
    (NOTIFICATION_APPLICATION_SCHEDULED_FOR_INTERVIEW, "Your application has been scheduled for an interview"),
)
