# Generated by Django 5.0 on 2024-01-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
