# Generated by Django 5.0.4 on 2024-07-20 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_is_archived_archivedmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='archivedmessage',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='archivedmessage',
            constraint=models.UniqueConstraint(fields=('user', 'message'), name='unique_user_message'),
        ),
    ]
